### ISSUE TITLE
cannot create filter with webapp starter

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#35]
I have the starter up and runing. I cannot see user tasks for the given sample process because no tasklist filters are active and I cannot create new ones. Anyone has the same problem?

**Comment by meyerdan** [comment]
Hi Jan,

what do I have to do to start it?

Daniel

**Comment by jangalinski** [comment]
Just run the Application in examples webapp. https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/examples/camunda-spring-boot-starter-example-webapp/src/main/java/org/camunda/bpm/spring/boot/starter/example/webapp/Application.java    The webapp is then accesible under http://localhost:8080/   you will need to created an admin user and then manually start the process instance via tasklist. Thanks for looking into this.

**Comment by meyerdan** [comment]
Hi Jan,

can I run https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/examples/camunda-spring-boot-starter-example-webapp/src/main/java/org/camunda/bpm/spring/boot/starter/example/webapp/Application.java 

from the cmd line or should I implort into Eclipse?

Sorry for asking such beginner questions...

**Comment by meyerdan** [comment]
I am running it from eclipse :dancer:

**Comment by jangalinski** [comment]
Ah, I assumed you had the project in your IDE. If not, just use maven https://docs.spring.io/spring-boot/docs/current/maven-plugin/run-mojo.html

**Comment by meyerdan** [comment]
I have it running. When I press F12 in the tasklist I see a JS error in the console. Will investigate

**Comment by meyerdan** [comment]
hi Jan,

What is the value of the Process Engine Configuration setting "authorizationEnabled"? Is it set to false? 
Could you try with setting that to true? I do not know how to configure this myself and christian is busy :D 

daniel

**Comment by osteinhauer** [comment]
Hi Daniel.

The authorization properties are „camunda default values“.

But I have created a #35 branch and added the possibility to configure authorization. 

You can put a file named application.properties in the src/main/resources folder and play with the properties:

camunda.bpm.authorization.enabled=true/false
camunda.bpm.authorization.enabled-for-custom-code=true/false

**Comment by osteinhauer** [comment]
By the way: If you install the springsource toolsuite plugin in eclipse you can use autocompletion in property files 😉

**Comment by meyerdan** [comment]
I found the problem. If you log into tasklist and inspect the requests that are performed (by opening DEV tools), then you see that an OPTIONS request on the filter resource comes back 200 OK but without any content. I placed a breakpoint in the method it shoud invoke in the backend and see that the method never gets called.

![image](https://cloud.githubusercontent.com/assets/488063/12511686/92f2ae24-c113-11e5-9467-44fe12c7b21e.png)


The underlying problem is that the javascript in the Webapp sets the wrong accept headers

```
Accept: application/hal+json, application/json; q=0.5
```

while it should be 

```
Accept: application/json
```

Why is this not always a problem?
The spring boot starter uses a jersey version which we do not test in combination with the webapp.

To fix this in the correct way we would need to make sure the Tasklist JS code sets the correct accept header.

But we cannot change the 7.4.0 js code since it is already released.

Two options:
1. release the spring boot extension and accept this as a known limitation and fix the bug for the next spring boot release. Which could be just 3 days later!!!
2. try to fix the bug before the release

I strongly advise to go for option 1. Why? => there is an unlimited number of bugs anyway this is just one we know about by accident. While fixing it, we may discover 100 other bugs and if we want to fix them too, then we will never perform a release.

Daniel

**Comment by meyerdan** [comment]
See: https://app.camunda.com/jira/browse/CAM-5299

**Comment by jangalinski** [comment]
I tried this with 7.4.5-ee which should fix the issue, but have the same problem: create filter is not visible, no filter-> no tasks ...  ideas?

**Comment by justinwyer** [comment]
This is still a problem in 7.5.0-alpha3, the 7.4.0 webjar's are present.

**Comment by jangalinski** [comment]
There is more to it:

1. webjars are not part of the bom, so you have to manually import them and set the correct version - https://app.camunda.com/jira/browse/CAM-5704
2. webjars are broken (not built) in alpha2 and alpha3 - https://app.camunda.com/jira/browse/CAM-5707

**Comment by hawky-4s-** [comment]
Hi Jan, did you test the issue with the new webjar already?

**Comment by jangalinski** [comment]
not with 7.5 alpha. with 7.4.5 it did not work

**Comment by ronalders** [comment]
This is fixed when you explicitly upgrade the webjars to 7.5.0 CE. I tested it and it workes fine now, i thank this issue can be closed now.

**Comment by jangalinski** [comment]
Thanks for testing. Thats good news. I guess we should switch to 7.5 for 1.2 then. Objections?

**Comment by jangalinski** [comment]
fixed via #94
