### ISSUE TITLE
Cannot use embedded forms on the app

### ISSUE THREAD

**Issue by lockoff** [camunda/camunda-bpm-spring-boot-starter#39]
Hello,

I've been working on an application using the webapp starter, and have been trying to get an embedded form to work. My project structure is very similar to the one found in `examples/camunda-spring-boot-starter-example-webapp`. I tried creating a folder `src/main/webapp/forms` with a file `greetingForm.html` , and modifying `sample.bpmn` so that the user task "do something" has form key `app:embedded:forms/greetingForm.html`, but I get a CORS error displayed when trying to view the form in the Tasklist. 

We experienced a similar problem with a non-spring-boot Camunda project, and the issue went away when we used an `META-INF/process.xml` without any configuration, like:

```
<?xml version="1.0" encoding="UTF-8" ?>
<process-application
    xmlns="http://www.camunda.org/schema/1.0/ProcessApplication"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <process-archive>
    <process-engine>default</process-engine>
    <properties>
    </properties>
  </process-archive>
</process-application>
```

but the same approach doesn't seem to work here. The problem seems to involve the `contextPath` being `null` in the response below, which is obtained by tasklist app when using the API endpoint `/api/engine/engine/default/task/1408`

```
{"key":"embedded:app:forms/greetingForm.html","contextPath":null}
```

Can embedded forms work with the spring boot webapp starter? Is this a bug, pending feature, or something I'm missing? Thanks!

**Comment by osteinhauer** [comment]
Hi.

IMHO: never tried that. Could you please provide an example project (on github)?

**Comment by lockoff** [comment]
Sure! Please [checkout my fork of the repo](https://github.com/lockoff/camunda-bpm-spring-boot-starter/tree/embedded-forms), branch `embedded-forms` off tag `1.1.0` (the version we're using, but this same problem exists on `master`). 

`examples/camunda-spring-boot-starter-example-webapp` has been modified so that `sample.bpmn` uses an embedded form in the "do something" task. The form is located at `src/main/webapp/greetingForm.html`. If you start the example with `mvn spring-boot:run`, make your way to the tasklist, start the `Sample` process, and click on the task that's assigned to you when the process starts (I use the notification about the task being assigned to me that pops up in the bottom right) you encounter the error.

Thanks for the help!

**Comment by lockoff** [comment]
If it helps, I'm working off of [this example](https://docs.camunda.org/manual/7.4/user-guide/task-forms/#embedded-task-forms) from the Camunda docs.

**Comment by lockoff** [comment]
We have a workaround, but I tracked down more of an exact cause using my debugger and wanted to share. Because there is no process engine application (sometimes called a process archive) associated with the SpringAutoDeployment, the context path for the application cannot be retrieved, and this results in the embedded form key not being translated.

More precisely, the relevant portion of the call stack in Camunda 7.4 looks like:

```
....
ManagementServiceImpl#getProcessApplicationForDeployment(String): 86
ApplicationContextPathUtil#getApplicationPathForDeployment(ProcessEngine, String): 42
TaskResourceImpl#getForm(): 197
```

The `TaskResourceImpl` tries to set the context path in the `FormDto` that gets returned as the response to the task form endpoint. `ApplicationContextPathUtil` tries to retrieve the context path by querying the `ManagementServiceImpl` for the process application name. The management service returns `null` for the process application name, because there is no process application associated with the deployment. As a result, `ApplicationContextPathUtil` returns `null` for the context path, this is what gets set in the `FormDto`, and as a result the frontend cannot translate the form key into an actual URL. 

If it were possible to associate a process application / process archive with the auto-created deployment, I believe that would resolve the issue.

Hope this helps. Please at-me if I can answer any questions.

**Comment by jangalinski** [comment]
I think it would be a good idea to use an ProcessApplication, see



    https://forum.camunda.org/t/formkey-resolve-embedded-app-fails-with-spring-boot/479
    https://docs.camunda.org/manual/7.4/user-guide/process-applications/the-process-application-class/#the-embeddedprocessapplication

This might also solve #53 ... we just use processapplication.deploy instead of implementing our own resource-parser

**Comment by jangalinski** [comment]
Fixed by #76 

Using the SpringBootProcessApplication 

```java
@SpringBootApplication
public class MyApp extends SpringBootProcessApplication {}
```

fixes this issue by adding a `servletContextPath="/"`property to the application which is used by the formService to resolve the ":app:" identifier.

**Comment by mcs** [comment]
Well, the same problem occurs for me when using Spring Boot 2.0.2, but setting server.servlet.contextPath doesn't fix it for me. I don't even get an error in my server log, just an invalid HTTP request to `http://localhost:8080/forms/ergebnis-lesen.html?noCache=1529563649812&taskId=f5ddea46-751e-11e8-870f-aced5cb84e54&userId=demo`

I am using the camunda-bpm-spring-boot-starter-webapp-ee with version 3.0.0.

**Comment by jangalinski** [comment]
I would suggest to raise a support ticket
